Optionally log request details on m3ql request error
Example curl with unknown remote cluster:
```
curl -s -XPOST 'localhost:9200/_m3ql?start=now-1h&end=now&explain=false&pushdown=true' \
    -H 'Content-Type: application/json' \
    -d '{
    "query": "fetch service:api | moving 5m sum",
    "resolved_partitions": {
      "partitions": [
        {
          "fetch_statement": "service:api",
          "partition_windows": [
            {
              "partition_id": "cluster1:index-a",
              "start": "2025-12-13T00:44:49Z",
              "end": "2025-12-13T02:14:49Z",
              "routing_keys": [
                {"key": "service", "value": "api"},
                {"key": "region", "value": "us-west"}
              ]
            },
            {
              "partition_id": "cluster2:index-b",
              "start": "2025-12-13T02:14:49Z",
              "end": "2025-12-13T04:14:49Z",
              "routing_keys": [
                {"key": "service", "value": "api"},
                {"key": "region", "value": "us-east"}
              ]
            }
          ]
        }
      ]
    }
  }'
```

Without logger enabled: no logs.

Enable logger:
```
curl -s -XPUT 'localhost:9200/_cluster/settings' \
    -H 'Content-Type: application/json' \
    -d '{
    "transient": {
      "logger.org.opensearch.tsdb.query.rest.RestM3QLAction.verboseLogger": "DEBUG"
    }
  }'
  ```

```
[2026-02-28T00:16:03,689][DEBUG][o.o.t.q.r.R.verboseLogger] [integTest-0] Failed to resolve index settings for M3QL request: query='fetch service:api | moving 5m sum', start=1772234163686, end=1772237763686, indices=cluster1:index-a,cluster2:index-b, explain=false, pushdown=true, profile=false, include_metadata=false, federation_metadata=ResolvedPartitions{partitions=[ResolvedPartition[fetchStatement=service:api, partitionWindows=[PartitionWindow[partitionId=cluster1:index-a, startMs=1765586689000, endMs=1765592089000, routingKeys=[service:api, region:us-west]], PartitionWindow[partitionId=cluster2:index-b, startMs=1765592089000, endMs=1765599289000, routingKeys=[service:api, region:us-east]]]]]}, ccs_minimize_roundtrips=true, body={
    "query": "fetch service:api | moving 5m sum",
    "resolved_partitions": {
      "partitions": [
        {
          "fetch_statement": "service:api",
          "partition_windows": [
            {
              "partition_id": "cluster1:index-a",
              "start": "2025-12-13T00:44:49Z",
              "end": "2025-12-13T02:14:49Z",
              "routing_keys": [
                {"key": "service", "value": "api"},
                {"key": "region", "value": "us-west"}
              ]
            },
            {
              "partition_id": "cluster2:index-b",
              "start": "2025-12-13T02:14:49Z",
              "end": "2025-12-13T04:14:49Z",
              "routing_keys": [
                {"key": "service", "value": "api"},
                {"key": "region", "value": "us-east"}
              ]
            }
          ]
        }
      ]
    }
  }
org.opensearch.tsdb.query.rest.IndexSettingsResolutionException: Failed to fetch settings from remote partitions [cluster1:index-a, cluster2:index-b]: Failed to fetch settings from remote cluster: cluster1 indices [index-a]: no such remote cluster: [cluster1]
        at org.opensearch.tsdb.query.rest.RestM3QLAction$3.onFailure(RestM3QLAction.java:758)
        at org.opensearch.tsdb.query.rest.RemoteIndexSettingsCache$1.onFailure(RemoteIndexSettingsCache.java:397)
        at org.opensearch.tsdb.query.rest.RemoteIndexSettingsCache$2.onFailure(RemoteIndexSettingsCache.java:532)
        at org.opensearch.tsdb.query.rest.RemoteIndexSettingsCache.fetchIndexSettingsFromRemoteClusterAsync(RemoteIndexSettingsCache.java:613)
        at org.opensearch.tsdb.query.rest.RemoteIndexSettingsCache.fetchAllClustersAsync(RemoteIndexSettingsCache.java:472)
        at org.opensearch.tsdb.query.rest.RemoteIndexSettingsCache.getIndexSettingsAsync(RemoteIndexSettingsCache.java:377)
        at org.opensearch.tsdb.query.rest.RestM3QLAction.getDefaultStepFromIndexSettingsAsync(RestM3QLAction.java:707)
        at org.opensearch.tsdb.query.rest.RestM3QLAction.parseRequestParams(RestM3QLAction.java:492)
        at org.opensearch.tsdb.query.rest.RestM3QLAction.parseRequestParamsAsync(RestM3QLAction.java:406)
        at org.opensearch.tsdb.query.rest.RestM3QLAction.lambda$prepareRequest$0(RestM3QLAction.java:211)
        at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:132)
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:383)
        at org.opensearch.rest.RestController.tryAllHandlers(RestController.java:473)
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:289)
        at org.opensearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:374)
        at org.opensearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:482)
        at org.opensearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:357)
        at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:60)
        at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:44)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at org.opensearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:72)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:120)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:170)
        at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:48)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:91)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:434)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:361)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:325)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:249)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:270)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:553)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:484)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:293)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:172)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.handle(AbstractNioChannel.java:445)
        at io.netty.channel.nio.NioIoHandler$DefaultNioRegistration.handle(NioIoHandler.java:388)
        at io.netty.channel.nio.NioIoHandler.processSelectedKey(NioIoHandler.java:596)
        at io.netty.channel.nio.NioIoHandler.processSelectedKeysPlain(NioIoHandler.java:541)
        at io.netty.channel.nio.NioIoHandler.processSelectedKeys(NioIoHandler.java:514)
        at io.netty.channel.nio.NioIoHandler.run(NioIoHandler.java:484)
        at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:225)
        at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:196)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1195)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: java.lang.RuntimeException: Failed to fetch settings from remote cluster: cluster1 indices [index-a]: no such remote cluster: [cluster1]
        ... 61 more
Caused by: org.opensearch.transport.NoSuchRemoteClusterException: no such remote cluster: [cluster1]
        at org.opensearch.transport.RemoteClusterService.getRemoteClusterClient(RemoteClusterService.java:418)
        at org.opensearch.transport.client.node.NodeClient.getRemoteClusterClient(NodeClient.java:155)
        at org.opensearch.tsdb.query.rest.RemoteIndexSettingsCache.fetchIndexSettingsFromRemoteClusterAsync(RemoteIndexSettingsCache.java:572)
        ... 60 more
```

To disable it again:
```
  curl -s -XPUT 'localhost:9200/_cluster/settings' \
    -H 'Content-Type: application/json' \
    -d '{
    "transient": {
      "logger.org.opensearch.tsdb.query.rest.RestM3QLAction.verboseLogger": null
    }
  }'
```

Signed-off-by: phiiip <22754958+philiplhchan@users.noreply.github.com>